### ISSUE TITLE
Failure to Initialize

### ISSUE THREAD

**Issue by Drownx** [netpyoung/SqlCipher4Unity3D#11]
Hi, i got everything working fine in editor, using both datapath and persistent data path to store my DB, but on Android >= 6.0 it just shows the message "Failure to initialize! Your hardware does not support this application, sorry". I Tested on 3 devices with different android versions.

On 5.0 it opens the game, but the DB still doesn't work.

However, the same project and code works fine with Sqlite3 on every device (Ios or Android).

**Comment by netpyoung** [comment]
Okay I will check.
Could you tell me what's the version of Unity?

and Could you try using this https://github.com/netpyoung/SqlCipher4Unity3D/blob/573f8dd855419432ea65eaae9181cff4f93f56eb/SqlCipher4Unity3D.unitypackage .

**Comment by Drownx** [comment]
Sure, i'm using 2017.1.1p4. Didn't test on other versions yet.
I'll try that package tomorrow, thanks!

**Comment by netpyoung** [comment]
I tested.

But It looks working fine 
```
unity
- 2018.2.2f1
- minimum 5.1 api level 22
- gradle
device
- android 5.1 
- created by memu
```

https://github.com/netpyoung/SqlCipher4Unity3D/blob/master/SqlCipher4Unity3D-v1.0.0.unitypackage

**Comment by Drownx** [comment]
Just tested your package, still getting the same error.
```
- 2017.1.1p4. (Working fine in editor and standalone)
- Minimum 5.0 api level 21
- gradle
- "Failure to Initialize" on Android 6.0 and 7.0. Can't even open the application.
```

**Comment by netpyoung** [comment]
That's interesting. It seems some problem on Android 6.0.
But I don't have test device for that.
Let me check thinking about testing.

**Comment by netpyoung** [comment]
outdated.
