### ISSUE TITLE
little error in example. but Thank you to your nice work.

### ISSUE THREAD

**Issue by foenix76** [netpyoung/SqlCipher4Unity3D#12]
Thanks to your work. It was easy to use!
But some error in example.
CreateDBScript bind twice at each two gameObjects (@CreateDBScript & Main Camera) at example.
(It's not critical. just little error..)
Sorry for my broken English. one more Thank you!

NullReferenceException: Object reference not set to an instance of an object
example.CreateDBScript.ToConsole (System.String msg) (at Assets/example/CreateDBScript.cs:38)
example.CreateDBScript.ToConsole (System.Collections.Generic.IEnumerable`1[T] people) (at Assets/example/CreateDBScript.cs:33)
example.CreateDBScript.StartSync () (at Assets/example/CreateDBScript.cs:25)
example.CreateDBScript.Start () (at Assets/example/CreateDBScript.cs:16)

**Comment by netpyoung** [comment]
@foenix76  Thank you for report that. I will check it later.
감사합니다.
