### ISSUE TITLE
ReKey database

### ISSUE THREAD

**Issue by aberestovskyi** [netpyoung/SqlCipher4Unity3D#13]
Hi, how I can set/change password for database which wasn't encrypted?

**Comment by netpyoung** [comment]
you can using sqlcipher-api `Key`

* https://www.zetetic.net/sqlcipher/sqlcipher-api/#key
* https://github.com/netpyoung/SqlCipher4Unity3D/blob/c6157c07733f8b77ad85adb3e068818f0e773665/SqlCipher4Unity3D/Assets/SqlCipher4Unity3D/Sqlite3.cs#L134

**Comment by netpyoung** [comment]
@aberestovskyi plz reopen this issue, If still have problem
