### ISSUE TITLE
64bit unity editor, sqlcipher.dll error

### ISSUE THREAD

**Issue by zobyzo** [netpyoung/SqlCipher4Unity3D#2]
error, in 64bit unity editor.
x64 sqlcipher.dll fix plz.

**Comment by netpyoung** [comment]
yes i will help you
could you describe your situation?
ex) reproduce process, your unity version, os, etc ...

**Comment by zobyzo** [comment]
window10, 
error on unity 5.5.2f1(64bit). 
unity 5.5.2f1(32bit) work fine.

**Comment by netpyoung** [comment]
I think it caused by lack of dependency of sqlcipher.dll.
sqlcipher need libeay32.dll.
so i upload libeay32.dll on my project, try again.

**Comment by zobyzo** [comment]
yes. thank you.
