### ISSUE TITLE
Support For Android arm64-v8a build

### ISSUE THREAD

**Issue by JinhyukLc** [netpyoung/SqlCipher4Unity3D#20]
[By Aug 2019, New and Updated apps must include a 64 bit version,](https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html) but this plugin doesn't seem to support arm64.
Thanks.

**Comment by netpyoung** [comment]
https://github.com/netpyoung/SqlCipher4Unity3D/blob/c6157c07733f8b77ad85adb3e068818f0e773665/SqlCipher4Unity3D/Assets/SqlCipher4Unity3D/Plugins/Android/libs/android-database-sqlcipher-3.5.9.aar

this file already contains library which support 64bit version
~~~
.
├── AndroidManifest.xml
├── aidl
├── android-database-sqlcipher-3.5.9.aar
├── assets
├── classes.jar
├── jni
│   ├── arm64-v8a
│   │   └── libsqlcipher.so
│   ├── armeabi
│   │   └── libsqlcipher.so
│   ├── armeabi-v7a
│   │   └── libsqlcipher.so
│   ├── x86
│   │   └── libsqlcipher.so
│   └── x86_64
│       └── libsqlcipher.so
├── libs
└── res
~~~
