### ISSUE TITLE
[Ignore] attribute doesn't work

### ISSUE THREAD

**Issue by Salbrox** [netpyoung/SqlCipher4Unity3D#23]
I have a property that I do not wish to be created in my db. I put the [Ignore] attribute before the property but it doesn't seem to work:

    public string ID { get; set; }
    public string CompanyID { get; set; }
    [Ignore]
    public Company Company
    {
        get
        {
            return DataService.SelectRecord<Company>("ID", CompanyID);
        }
        set
        {
            CompanyID = value.ID;
        }
    }
    public string UserName { get; set; }
    public string FullName { get; set; }`

When I run I get:

> NotSupportedException: Don't know about Company

**Comment by netpyoung** [comment]
Sorry I  cannot fully understand your current situation.

I added test code then the test was passed
 
Could you review that?

- https://github.com/netpyoung/SqlCipher4Unity3D/blob/51250ca00d0dc6a65b9f84261de9daa5bf50e486/SqlCipher4Unity3D/Assets/test/Editor/IgnoreTest.cs#L87

**Comment by Salbrox** [comment]
I tried the test and it passes. But the issue still persists in my code. The [Ignore] attribute still does not work. I cannot see what I might be doing wrong.

**Comment by netpyoung** [comment]
Could you check this attribute is correct?
```
using IgnoreAttribute = SQLite.Attribute.IgnoreAttribute;
```
I suspicious that line
```
        return DataService.SelectRecord<Company>("ID", CompanyID);
```
Could you try make empty table then check the result of that?
```
            Conn.CreateTable<Company>();
```

**Comment by Salbrox** [comment]
I was using the wrong lib. I removed it and added:

`using IgnoreAttribute = SQLite.Attribute.IgnoreAttribute;`
`using PrimaryKeyAttribute = SQLite.Attribute.PrimaryKeyAttribute;`

Its working fine now. Thanks for your help.
