### ISSUE TITLE
File is encripted or is not a database

### ISSUE THREAD

**Issue by AndradeSoto** [netpyoung/SqlCipher4Unity3D#24]
Hello
 
I imported the examples and test SQLitetest scen and works fine, but the SQLCipherTest scene doesn´t work fine

The scene created the database and is correctly encrypted, but when unity try to open I have an error

`SqliteException: file is encrypted or is not a database FullQuery=|delete from UserData;|(ErrorCode:26)
SqliteDatabase.Prepare (System.String query) (at Assets/Plugins/SqliteDatabase.cs:400)
SqliteDatabase.ExecuteNonQuery (System.String query) (at Assets/Plugins/SqliteDatabase.cs:263)
SQLSample.Start () (at Assets/Tests/Scripts/SQLSample.cs:30)
`

I know the database was made correctly because I used DB Browser(SQLCipher) to open the file/database and is opened correctly

Only with unity can't opent the database.

**Comment by netpyoung** [comment]
Which SqlCipher version had been used?

 Current Sqlcipher4Unity3D using v3 encription. I have a plan to support v4 but I don't have mac and test device for ios so It having been delayed.

It seems to using SqiCipher v4.(default for DB Browser). Could you check the encryption settings?

![Annotation 2019-11-08 173250](https://user-images.githubusercontent.com/335121/68461559-d3f4e200-024d-11ea-8ef1-fbab1636a046.png)

**Comment by AndradeSoto** [comment]
When I run the SQLCipherTest scene it creates the database, with password 'password', then Unity try to open and write data, but I get this error.

![Captura de pantalla (71)](https://user-images.githubusercontent.com/23009179/68502411-924c4300-021d-11ea-892f-aa151ecdc405.png)

But I can open the database with DB Browser(SQLCipher) select v3

![Captura de pantalla (76)](https://user-images.githubusercontent.com/23009179/68503203-8e212500-021f-11ea-99d5-d1c638196eb6.png)

![Captura de pantalla (76)](https://user-images.githubusercontent.com/23009179/68503275-b27d0180-021f-11ea-8605-005bd66dbed4.png)

The database is created, but Unity can´t to open it.

**Comment by netpyoung** [comment]
Um that's interesting. Could you share the db file, password and some snippet code for open that file?

**Comment by AndradeSoto** [comment]
https://github.com/AndradeSoto/TestEncrypt

I just did a project and imported your example, this is the code, the password to database is "password".

**Comment by netpyoung** [comment]
Thank you share your project for checking.

I checked your repo then I found that you are using other library. So I can't help to solve that problem.

Could you trying this project's library?
 
- [Repo](https://github.com/netpyoung/SqlCipher4Unity3D)
- [Unitypackage](https://github.com/netpyoung/SqlCipher4Unity3D/raw/master/SqlCipher4Unity3D-v1.0.1.unitypackage)
- [Example](https://github.com/netpyoung/SqlCipher4Unity3D/tree/master/SqlCipher4Unity3D/Assets/example)

If you have any problem to using this library, feedback to me. I can help you gladly.

**Comment by netpyoung** [comment]
@AndradeSoto Because, That's not associated with this project, so I close this issue.
If any problem of using this library please create another issue for that.
