### ISSUE TITLE
Unity Package link broken

### ISSUE THREAD

**Issue by cstehreem** [netpyoung/SqlCipher4Unity3D#26]
HI,

The link to unity package on the readme seems to be broken: https://github.com/netpyoung/SqlCipher4Unity3D/raw/master/SqlCipher4Unity3D-v1.0.1.unitypackage

From where can I download it?

Thanks
Tehreem

**Comment by netpyoung** [comment]
Thank you for reporting.

I had uploaded that on release page. but It was missing.
So I reuploaded that.

Could you check release Page
https://github.com/netpyoung/SqlCipher4Unity3D/releases/tag/v1.0.2

- https://github.com/netpyoung/SqlCipher4Unity3D/releases/download/v1.0.2/SqlCipher4Unity3D-v1.0.2.unitypackage

**Comment by cstehreem** [comment]
Got it. Thank you for your extremely quick response. =)
