### ISSUE TITLE
dll for UWP

### ISSUE THREAD

**Issue by OldestDriver** [netpyoung/SqlCipher4Unity3D#29]
Is this support UWP?

**Comment by netpyoung** [comment]
I just pushed https://github.com/netpyoung/SqlCipher4Unity3D/commit/b7321eb2e83058844507bd38066789859b73b560 .

What I tested for x64 UWP release binary is work well on my local machine. but not other platform (I don't have Windows on ARM machine. )

**Comment by netpyoung** [comment]
@OldestDriver  I closed this issue cause without any feedback from that. If you have some problem plz raise new issue.
