### ISSUE TITLE
Unable to find sqlite 2.0.1 message popping up during startup (Android)

### ISSUE THREAD

**Issue by eos428** [netpyoung/SqlCipher4Unity3D#30]
Hi there.

When building and testing in Android, these two messages pop up in logcat, but not inside Unity itself.

![Screenshot 2020-10-08 114938](https://user-images.githubusercontent.com/38433056/95416361-bc8e0f80-095c-11eb-96e9-c5e7d34ed41a.jpg)

The plugin still works fine otherwise, but I'm a little wary these messages might get picked up by error reporting tools. Is it possible to remove this message?

Thanks in advance!

**Comment by netpyoung** [comment]
Thank you for reporting.

I added sqlite-2.0.1.aar which dependency of sqlcipher.aar.

I will check that.

**Comment by eos428** [comment]
Hello again.

Any updates regarding this issue?

**Comment by netpyoung** [comment]
Hi I'm pyoung.

I'm sorry to late reply. I totally forget this issue.

I reproduce that issue on my logcat, and I found how to solve this issue using `uncheck load on startup` on sqlite.aar

![Capture](https://user-images.githubusercontent.com/335121/101306323-efcf1b00-3887-11eb-8b1b-f45efbcccfea.JPG)

**Comment by netpyoung** [comment]
@eos428 Could you check that via uncheck load on startup?
then I will close this issue.

**Comment by eos428** [comment]
Hi @netpyoung 

I can confirm I am no longer receiving the issue on my logcat.
It's fine to close the issue now.

Thanks for your support!
