### ISSUE TITLE
Crashing On Huawei Devices

### ISSUE THREAD

**Issue by fani435** [netpyoung/SqlCipher4Unity3D#33]
I tested on multiple Huawei devices, and the app always crashes when I try to connect to the database. Here is how the connection is being made:

`_connection = new SQLiteConnection(dbPath, null);`

And here is the error I encounter while using Huawei P8:

> 11-18 13:52:21.329 15270 15684 E HAL     : load: id=gralloc != hmi->id=gralloc
11-18 13:52:21.337 15251 15700 E linker  : readlink('/proc/self/fd/40') failed: Permission denied [fd=40]
11-18 13:52:21.337 15251 15700 E linker  : warning: unable to get realpath for the library "/data/app/com.chisel.rawaan-1/lib/arm/libsqlcipher.so". Will use given name.
11-18 13:52:21.350 15251 15700 F art     : art/runtime/thread.cc:1326] No pending exception expected: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
11-18 13:52:21.350 15251 15700 F art     : art/runtime/thread.cc:1326] (Throwable with empty stack trace)
11-18 13:52:21.350 15251 15700 F art     : art/runtime/runtime.cc:368] Runtime aborting...
11-18 13:52:21.350 15251 15700 F art     : art/runtime/runtime.cc:368]
11-18 13:52:21.351 15251 15700 E CRASH   : signal 6 (SIGABRT), code -6 (?), fault addr --------
11-18 13:52:21.351 15251 15700 E CRASH   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-18 13:52:21.351 15251 15700 E CRASH   : Build type 'Release', Scripting Backend 'mono', CPU 'armeabi-v7a'
11-18 13:52:21.351 15251 15700 E CRASH   : Build fingerprint: 'HUAWEI/GRA-UL00/HWGRA:6.0/HUAWEIGRA-UL00/C185B391:user/release-keys'
11-18 13:52:21.351 15251 15700 E CRASH   : Revision: '0'

The same app works fine on other devices such as Redmi Note 8 and Samsung A71. The problem seems to only occur on Huawei devices.

Any help would be much appreciated.

**Comment by netpyoung** [comment]
Um.. that's strange.

Unfortunately I don't have Huawei device for test it.

I just assumed some cases.

- Check readwrite permissions for native library
- or sqlcipher's version problem
  - Could you try this sqlcipher3x version?? 
    https://github.com/netpyoung/SqlCipher4Unity3D/tree/v1.0.2

**Comment by netpyoung** [comment]
@fani435 there is no feed back from previous comment, so I decide to close this issue. If you have some problem plz create new issue.
