### ISSUE TITLE
Request to upgrade to SQLCipher 4.4.2

### ISSUE THREAD

**Issue by hanssnabilie** [netpyoung/SqlCipher4Unity3D#36]
I'm using SqLiteStudio and they don't have a version that supports 4.4.0 unfortunately. They have recently upgraded to 4.4.2 and editing anything will make the database unreadable for SqlCipher4Unity (4.4.0) Are there plans to upgrade to 4.4.2 by any chance?

Thanks

**Comment by netpyoung** [comment]
well... 
I tested my https://github.com/netpyoung/SqlCipher4Unity3D/blob/f9819ce1128f1e930a78c98c8b82e8bd981fd05e/SqlCipher4Unity3D/Assets/StreamingAssets/existing.db . It can be opened.

So Is it possible share example db file which doesn't opend in sqlitestudio? I will test that.

and To catchup latest version of sqlcipher is a little hard to me (Now I don't have mac machine... and I need to buy mac machine..) to build for mac machine.

But If you really want to use latest version of sqlcipher you can build with my build script.

**Comment by hanssnabilie** [comment]
Thank you for testing this for me. 

I decided to start a new project to doublecheck and it does indeed work fine. I must have another issue in my main project that is causing this, my apologies.
