### ISSUE TITLE
About adaptation to ILRuntime

### ISSUE THREAD

**Issue by 0x2CA** [netpyoung/SqlCipher4Unity3D#41]
[ILRuntime](https://github.com/Ourpalm/ILRuntime)

Thank you so much for your project .  But I now want to use it on ILRuntime,So need to adapt the reflection part.

**Comment by netpyoung** [comment]
Thank you your feed back.
But I don't have background knowledge about ILRuntime.
So Could you explain more detail about which part what you want to add feature?

**Comment by 0x2CA** [comment]
Thanks for your reply, I read your code, I reconstructed and deleted a lot of reflection related code, I directly used SQLite3 API, which can be used in my project (ILRuntime)
