### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by codercoder111** [netpyoung/SqlCipher4Unity3D#6]
is there a way to generate the encryption key and change the :
iterations
key length =128
algorithm = AES

Thanks

**Comment by netpyoung** [comment]
I think that is what you want. you can encrypt by binary key
https://github.com/sqlcipher/sqlcipher#encrypting-a-database

https://github.com/netpyoung/SqlCipher4Unity3D/blob/master/SqlCipher4Unity3D/Assets/SqlCipher4Unity3D/Sqlite3.cs#L174

**Comment by codercoder111** [comment]
Yes that is what I want thank you ,I'm try to use it but gives me some problems about the DB pointer can you please write example how to use it when create database ?

Thanks

**Comment by netpyoung** [comment]
@codercoder111 what do you means about`SecureRandom`?

**Comment by netpyoung** [comment]
@codercoder111 plz reopen this issue if you didn't solve that problem or want to comment.
