### ISSUE TITLE
How to decrypt encrypted api response?

### ISSUE THREAD

**Issue by sonwani237** [netpyoung/SqlCipher4Unity3D#7]
Hello  everyone,
I am getting encrypted data from API how to decrypt it.

Encrypted Data-
p1SvSCiAxupKrrZXzjXQk48EeA7F1jnGymvqGlmAOMOrnUVZpopohJ8WYp/DI3nUuc4wG57FQWi2
TfwS+H7VSsanfbhKGf+i6H1iQchaSi9lgjxv96JCyhM9WaF7T9UuL5efwgwslGqGG54Ctx6Ykg==

Header data-
adrum_0 →clientRequestGUID:d792a1f7-dbe2-4c64-9d62-11c6fef8e3d3
adrum_1 →globalAccountName:customer1_198bbfab-6c90-48b0-bcaa-adad9ca335c4
adrum_2 →btId:7205
adrum_3 →btERT:276
adrum_4 →btDuration:315
connection →keep-alive
content-length →153
content-type →application/json;charset=UTF-8

It's decryption-
{
  "status": {
    "status": "500",
    "message": "Your request could not be served by the system. Please try again!"
  }
}

Thanks in advance Please solve it

**Comment by netpyoung** [comment]
sorry. I don't understand what's your intention.
Could you explain what you want more detail? thanks.

**Comment by netpyoung** [comment]
@sonwani237 This issue, seems not related on this project. so I close this issue.
If something wrong, plz reopen this issue, and explain more detail.
