### ISSUE TITLE
Updating libsqlcipher.so

### ISSUE THREAD

**Issue by codercoder111** [netpyoung/SqlCipher4Unity3D#8]
Hello

I'm tried to replace libsqlcipher.so with the new ones from "Zetetic" .
everything works good without password , but when I try to create or open DB with password , it gives error : not authorized can't open the database.

any solution ? Thank you

**Comment by netpyoung** [comment]
sorry for late reply. now days, I'm too busy for concerned others.
Could you share the project? and version of libsqlichiper.

**Comment by netpyoung** [comment]
@codercoder111 plz reopen this issue, If you still stucked on same problem.
